{
 "title": "Railway Documentation",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 15, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "# Railway Docs\n\n## readability\n\nThis dashboard tracks the readability of Railways's documentation over time. It uses the Flesch Reading Ease score (FRE) to calculate difficulty.\n\nThe FRE is a trusted metric developed in the 1970s by the United States Navy and it is still used throughout many industries around the globe.\n\nWith an upper boundary of `122` (e.g. \"The cat sat.\"), a score of `60` or higher is considered ideal for a general web audience. \n\nThe nature of technical documentation, however, makes this a challenging goal."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Docs Readability Distribution (based on Flesch Reading Ease Score)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 14, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "flesch_score{job=\"railway_docs\"}"
    }
   ]
  },
  {
   "title": "Average FRE for Railway Docs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "average_fre{job=\"railway_docs\"}"
    }
   ]
  },
  {
   "title": "FRE Distribution Over Time",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 8, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "flesch_score{job=\"railway_docs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FRE per URL",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "flesch_score{job=\"railway_docs\"}"
    }
   ]
  },
  {
   "title": "Total # of Docs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "docs_sum{job=\"railway_docs\"}"
    }
   ]
  },
  {
   "title": "Average FRE for Railway Docs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "average_fre{job=\"railway_docs\"}"
    }
   ]
  }
 ]
}